name: CI/CD Pipeline

on:
  - push
  - pull_request

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    services:
      redpanda:
        image: vectorized/redpanda:latest
        options: >-
            start
            --overprovisioned
            --smp 1
            --memory 128M
            --reserve-memory 0M
            --node-id 0
            --check=false
        ports:
          - 9092:9092

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

        #    - name: Prepare virtual environment
        #      run: make venv

    - name: Run tests
      run: make test

      #    - name: Run linter
      #      run: make lint

#  publish:
#    name: Publish package to PyPI
#    if: startsWith(github.ref, 'refs/tags')
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#    - uses: actions/checkout@v2
#
#    - uses: actions/setup-python@v2
#
#    - name: Publish package to PyPI
#      run: make release
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
